### ISSUE TITLE
Issues recreating raster layers like curtis data

### ISSUE THREAD

**Issue by auponchon** [TakahiroShimada/SDLfilter#1]
Hello,
I was very interested in using your package but unfortunately, I was unable to recreate the proper raster layers for the overlap function. Can you explain how you generated the curtis dataset? What are exactly the probabilities represented in the layers? How did you generate them from the filtered tracks? Thanks in advance for your response. I am looking forward to applying your functions further for my research.
Best regards,
Aurore Ponchon

**Comment by TakahiroShimada** [comment]
Dear Aurore,

Thanks for your email.

The raster layers are parts of the Utilisation Distributions estimated from the filtered data. The structure of the raster is very simple. Each raster layer has latitude, longitude and values in each grid cell. A value in each grid cell is the probability of the animal to be found within the cell. So if you sum up the values of all the grid cells, it should be 1 or very close to it.

The workflow to generate the raster layer would be;

  1.  Estimate a Utilisation Distribution (e.g. kernel density estimate) from each track. There are many options to estimate the UD from a track in R (e.g. adehabitatHR, ctmm) or ArcGIS (e.g. Kernel Density, Geospatial Modelling Environment). Please see the attached (Shimada et al 2016 and sup. info) for example. In this step, it is crucial that you specify a grid cell size (e.g. 50m) and the boundary of the estimation area (i.e. minimum and maximum lat and lon) that are consistent across different tracks.

  1.  The output from any of the above is an UD and essentially a raster layer. However each method would add extra information in their own format so you will need to extract the raster component manually. Unfortunately the extraction method would also vary by the UD estimation method that you use.

If you already have done the UD calculation (step 1) but are unsure how to extract the raster components, just give me a shout and I'm happy to help.

Best wishes,
Taka


________________________________

**Comment by TakahiroShimada** [comment]
Hi Aurore, I have added an example code that should address your question. 
See https://github.com/TakahiroShimada/SDLfilter#2-1-input-uds

This issue will be closed for now.
