### ISSUE TITLE
ddfilter

### ISSUE THREAD

**Issue by chanyingchi** [TakahiroShimada/SDLfilter#2]
Hi Takahiro,
I wonder why these columns are not returned:  "pTime", "sTime", "pDist", "sDist", "pSpeed", "sSpeed". I used a previous version and I got these columns but now not anymore (also tried it with your sample 'turtle' dataset, same outcome). Thanks!
Regards,
Ginny Chan

**Comment by TakahiroShimada** [comment]
Hi Ginny,
I updated the ddfilter function to include those values in the output. Please uninstall the version you have and install the development version from GitHub (see https://github.com/TakahiroShimada/SDLfilter). I plan to send this new version to CRAN sometime next week. 

You can also get those columns by using the track_param function. 
Please let me know if you still have any issues.

**Comment by chanyingchi** [comment]
Hi Takahiro,
Thanks for your quick response. I did not notice there is a track_param function before, that actually will serve my needs to get those values. Anyway it is good that those columns are added already with the ddfilter function. 
Regards,
Ginny
