### ISSUE TITLE
Package or namespace load failed for ‘SDLfilter’

### ISSUE THREAD

**Issue by aichi2020** [TakahiroShimada/SDLfilter#4]
Hi! Loading the library I have this error
"package or namespace load failed for ‘SDLfilter’:  package slot missing from signature for generic ‘coerce’
and classes STFDF, RasterBrick cannot use with duplicate class names (the package may need to be re-installed)"
I uninstalled and reinstalled it as suggested
1) from the CRAN: same problem
2) install_github("TakahiroShimada/SDLfilter"): same problem
However, the installation by both methods runs smoothly.
Currently running R version 4.2.2 (2022-10-31 ucrt) All the required packages are updated to this version. 
Obviously, I can't use any of the functions. I used the library in early October (previous SDLfilter’ and R versions) and worked fine.
Any idea, please? Thanks! 

UPDATE: At the time of updating R and reinstalling SDLfilter, the package "stars: Spatiotemporal Arrays, Raster and Vector Data Cubes" was updated to version 6.0. Updating this package solved the issue with SDLfilter.

**Comment by TakahiroShimada** [comment]
Hi is this still an ongoing issue?
