### ISSUE TITLE
Error in vmax calculation after ML parameter estimation

### ISSUE THREAD

**Issue by swforrest** [TakahiroShimada/SDLfilter#5]
Hi Takahiro,

Firstly, thanks for a great package. I have used the filtering method for several studies (although using the quantile vmax estimation) and found it very useful.

I believe I have found an error in the vmax function when estimating the **shape** and **rate** parameters of the Gamma distribution using maximum likelihood. The parameters are estimated correctly using the optim function, but when you then use those parameters to estimate the vmax, you use the pgamma function with the **shape** and the **scale** parameters, and as the scale is 1/rate, it defines the wrong Gamma distribution and gives wrong answers. The error is therefore on line 40/41. It is a very easy fix; the `scale = para$par[2]` on line 41 just needs to be changed to `rate = = para$par[2]`. I have tested this and it gives more correct answers. In the image below I have tested the ML and sample methods, and the corrected ML method. As you can see the original ML method gives erroneous results where the vmax increases for increasing qi (which seems implausible), whereas the sample quantiles and the corrected ML method agree fairly well (and vmax decreases with increasing qi).

![image](https://user-images.githubusercontent.com/94874698/210041915-bd14162c-0a6c-4865-a172-029e98fc01f9.png)

Also, why do transform the prob value using `p <- prob + (1 - prob)/2` in line 38? Why not just use the original probability value supplied to the function?

Kind regards,
Scott

**Comment by TakahiroShimada** [comment]
Hi Scott, thanks for your comments. I've fixed the issues and uploaded the new version to GitHub. Re transforming the prob value, it was a legacy from development and should not have been there. The new version uses the origianl probability value supplied to the function. I also added new arguments to distfilter and vmaxlp if you happen to use them (please see the news and help files for details).

Hope all bugs are fixed but please let me know if you find any.

Best wishes,
Taka

**Comment by TakahiroShimada** [comment]
The new version of the package is now available on CRAN.
