### ISSUE TITLE
Issue with ddfilter_speed with method = 2 when first or last point is an error

### ISSUE THREAD

**Issue by swforrest** [TakahiroShimada/SDLfilter#6]
Hi Takahiro,

Another issue from me, although this one only arises when using method = 2 (speed before OR after the location that is greater than the vmax is removed), and when the **speed succeeding the first point or preceeding the final point are greater than the vmax**. 

To provide an example, suppose that the final location is a large error, so that it's pSpeed will exceed the vmax (this was the case in our example). Therefore, the second to final point will have an sSpeed that exceeds the vmax. This penultimate point will be removed, but then because you have the while loop in the function that will continue to recalculate speeds and filter the data until sdata2 and sdata3 are equivalent, the new second to final point will have a sSpeed exceeding the vmax and will also be removed. This continues until all the data has been filtered out, and the function outputs something like the image below, where the only points left are the first, the last and in our case the second point:

![image](https://user-images.githubusercontent.com/94874698/229038163-19b94f8d-9c65-4cb1-965d-c779c25000c8.png)

This obviously doesn't happen with method = 1, as it is only the sSpeed of the penultimate point that exceeds the vmax.

A simple fix is to manually remove any first or last points that exceed the vmax (maybe due to deploying or retrieving the tag).

Although I have had a go at solving the problem within the code, which may not be an ideal solution, but something similar might be useful.

Firstly, in lines 34-43 of the function you have that if the pSpeed or sSpeed exceed the vmax, they are assigned a 0, but also that they must not be NA, which I'm assuming is so the conditional expression doen't break from NA values. In this way the first and last values are always retained, as they will always have an NA because they don't have a preceeding or succeeding point, respectively.

```R
if (method == 2) {
        overMax <- function(i) if ((sdata$pSpeed[i] > 
          vmax | sdata$sSpeed[i] > vmax) && (!is.na(sdata$pSpeed[i])) && 
          (!is.na(sdata$sSpeed[i]))) {
          0
        }
        else {
          1
        }
      }
```

I have changed this to have the OR statement between the conditions for each speed, i.e., if the speed exceeds the vmax AND is not NA, then it will be assigned a 0 and later removed.

```R
if (method == 2) {
        overMax <- function(i) if ((sdata$pSpeed[i] > 
          vmax && !is.na(sdata$pSpeed[i])) | 
          (sdata$sSpeed[i] > vmax && !is.na(sdata$sSpeed[i])))
           {
          0
        }
        else {
          1
        }
      }
```

But then in lines 44-52 of the function, you are assessing each location between the start and end locations within each individual, but these are indexed from the second to the second to last point, I'm guessing because of the NAs:

```R
set.rm <- function(j) {
  start <- as.numeric(rownames(sdata[sdata$id %in% 
    j, ][2, ]))
  end <- as.numeric(rownames(sdata[sdata$id %in% 
    j, ][1, ])) + (nrow(sdata[sdata$id %in% j, 
    ]) - 2)
  rm <- unlist(lapply(start:end, overMax))
  c(1, rm, 1)
}
```

I changed this to index from the first to last point within each individual, and then c(1, rm, 1) also isn't required :

```R
set.rm <- function(j) {
  start <- as.numeric(rownames(sdata[sdata$id %in% 
    j, ][1, ]))
  end <- as.numeric(rownames(sdata[sdata$id %in% 
    j, ][1, ])) + (nrow(sdata[sdata$id %in% j, 
    ]) - 1)
  rm <- unlist(lapply(start:end, overMax))
}
```

After giving it a try with both method 1 and 2 it seems to solve the problem, although it may have introduced problems I haven't anticipated.

![image](https://user-images.githubusercontent.com/94874698/229042468-e0247290-5766-4b1e-b801-78079330cb1f.png)

The only edits I made were changing the location of the OR in the if-else statement, and then the indexing for each individual.

Hopefully that's helpful. If the solution can't be implemented or doesn't work on conditions other than what I tested it on then it might be worth including a brief word of caution to check if the first or last points exceed the vmax when using method = 2.

Kind regards,
Scott

**Comment by TakahiroShimada** [comment]
Hi Scott, thanks for reporting this. While fixing the bug that you pointed out, I also became aware of another issue. Previously when method 2 was selected, the filter removed all the successive locations where the speed from the last OR next locations (i.e. pSpeed, sSpeed) exceeded the vmax. This may have removed some good locations as well as inaccurate ones in situation when some of the successive locations were accurate but were associated with large pSpeed or pSpeed values due to inaccuate succeeding or preceeding locations.  This is now fixed. Please also see the updated help file for ddfilter_speed - method. 

This patch is now applied in the dev version on GitHub (2.3.1.9003) and will be pushed to CRAN in the nearby future. Please let me know if there is an issue.
Best wishes,
Taka

**Comment by TakahiroShimada** [comment]
The new version (2.3.2) is on its way to CRAN.

**Comment by swforrest** [comment]
Hi Takahiro,
Great! My colleague and I had also noticed this issue, so we are glad you were able to fix that too. It looks like a nice solution. We will use the dev version until the CRAN version comes out. Thanks for getting onto this so quickly.
Kind regards,
Scott
