### ISSUE TITLE
plotKML will fail CRAN checks from 16 October, taking SDLfilter with it

### ISSUE THREAD

**Issue by rsbivand** [TakahiroShimada/SDLfilter#7]
@TakahiroShimada  plotKML has not been updated to remove dependency on rgdal or maptools by the 16 October deadline https://github.com/Envirometrix/plotKML/issues/14. Because SDLfilter imports plotKML, it will also fail when plotKML gets archived (17-18 October). Pleae try to move plotKML to suggests and condition on all use (code, vignettes, examples, demos, etc.). See https://r-spatial.github.io/evolution/ for details.

**Comment by TakahiroShimada** [comment]
Thanks for your comments. plotKML has been removed from SDLfilter and the new version is on its way to CRAN.
